### ISSUE TITLE
Tasks/Activities and Multiple Contacts in Name (WhoID) field -DLRS only works for one of the Contacts

### ISSUE THREAD

**Issue by JTPropst** [SFDO-Community/declarative-lookup-rollup-summaries#1029]
We currently use NPSP and have a DLRS that displays the name of the user that last created a Task/Activity for a Contact on that Contact's Record page. The standard Name (WhoId) field allows the user to links multiple Contacts to a single Task. When a user links two or more Contacts to a Task/Activity using the Name (WhoId) field the DLRS will only update the first Contact linked to the Task/Activity. For example, user named John Doe links a single Task/Activity to a Husband and Wife in the same Household using the Name (WhoId) field. The Husband's Contact record will display John Doe from the DLRS but the field on theWife's contact record will remain blank. Is there a workaround or something extra I need to do on the DLRS? I know that the Task/Activity lookups are more difficult than normal as they can relate multiple records at once and also relate records from different objects in the same lookup.

**Comment by aheber** [comment]
@JTPropst I hope you were able to get this resolved. On chance you weren't I'd recommend you take a look at the TaskRelation object.
https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_taskrelation.htm

This is the Salesforce object that actually connects multiple contacts to an individual Task/Activity. If you want to rollup to every contact connected to a Task you'll have to configure your rollup to work with those objects as well. It might get a little tricky because you're likely pulling data from multiple possible objects to help assemble this data set for the Contact record.

I'll move this to closed, if you need additional support I'd recommend you connect with the wonderful Trailblazer Community Group which is our recommended path to getting support from our community of awesome experiences users.

**Comment by JTPropst** [comment]
@aheber  Thanks for the update!  We decided to not use DLRS and instead leverage Salesforce Flow as it gave us a much more flexibility working with the TaskWhoRelation object.

**Comment by aheber** [comment]
Great! Thanks for letting me know.
