### ISSUE TITLE
Multiselect value in Relationship Criteria firing null value when blank

### ISSUE THREAD

**Issue by tcharles12** [SFDO-Community/declarative-lookup-rollup-summaries#1102]
I edited this post at the bottom after further testing!*

Hello! I'm running into an issue where I'm referencing a multiselect field value in my DLRS relationship criteria, along with 2 other criteria, but when that multiselect field is null, the DLRS is still firing and is rolling up a blank value to the arregate result field.

Below is my Relationship Criteria, and I've also included a screenshot of the full config.
(npe5__Status__c = 'Current' AND Contact_For__c INCLUDES ('Primary Contact') AND Fund_Affiliation__c = TRUE)

![Screen Shot 2021-11-02 at 6 07 37 PM](https://user-images.githubusercontent.com/42197522/139982938-30f0bdf7-f151-4a44-8e00-b70e5667f5af.png)

When I remove this portion of the criteria: **Contact_For__c INCLUDES ('Primary Contact')**, the DLRS works correctly and does not fire the null value as described above, so that piece of it _seems_ to be the culprit, but I'd love any insight/confirmation on what I'm missing here.

Thanks!

*EDIT TO ADD: The multiselect field isn't actually the culprit. It seems that this DLRS is firing on every Affiliation record edit, even if I'm only editing a custom field that is not the Field to Aggregate or in the Relationship Criteria. My understanding is that DLRS should only fire in realtime on edits to those fields. I wonder if NPSP Triggers on the Affiliation object are somehow enabling the DLRS to fire unnecessarily. Any thoughts?

**Comment by tcharles12** [comment]
Hi @afawcett ! Any ideas on this case? I have a DLRS that is firing on every record edit, not just when the relationship criteria fields are edited. Thanks!

**Comment by aheber** [comment]
@tcharles12, this project typically provides support through the Trailhead community group. https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5p

I'll do my best to be helpful but you'll likely get more help through that channel.

Can you help me understand the records in this case? Do you have any records that meet the criteria for that parent record? A DLRS job, configured as you have it, would make sense to place a blank value in the parent if there are no children meeting criteria. DLRS still updates the parent when a new child is added or a tracked field is modified, even if the record that was edited doesn't match the criteria. This is to help keep the parent up to date. When DLRS decides to process that parent, due to a child being edited, it doesn't yet know if there is a meaningful change on the end result. Any time a child is created or edited with any of the Relationship Field, Field to Aggregate, or any of Relationship Criteria Fields modified then it queues up that parent record for recalculation. That might result in a blank value if no records currently match the Relationship Criteria.

If I don't understand your question or problems correctly please help me understand. Thanks!

**Comment by tcharles12** [comment]
Hi @aheber - Thank you for your thoughts on this! I [posted](https://trailhead.salesforce.com/trailblazer-community/feed/0D54S00000DxisZSAR) in the community group. 

Do you happen to know if there's any way to configure the rollup so that a null value will not overwrite any existing value in the Aggregate Result Field in the event that the child records do not meet the criteria? I see there was a similar [idea](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/issues/521), but it doesn't seem to have been delivered yet.

**Comment by aheber** [comment]
As far as I can think right now, no. DLRS takes ownership of the destination field and thinks it need to "correct" that value every time it thinks it changes.

I know defining "empty" behaviors has been oft requested but isn't on top of the backlog right now.

**Comment by tcharles12** [comment]
Gotchya, okay, thank you very much for your replies! Appreciate it.
