### ISSUE TITLE
Read Only

### ISSUE THREAD

**Issue by Stephen-J-Russell** [SFDO-Community/declarative-lookup-rollup-summaries#1185]
I have my Aggregate Result Fields set to Read Only yet it seems all users are able to edit these fields.  Can you help by telling me what I am doing wrong?

**Comment by dicksonstephen** [comment]
Hi @Stephen-J-Russell - the best place for support is generally the DLRS Community at https://trailhead.salesforce.com/trailblazer-community/groups/0F9300000009O5pCAE?tab=discussion, but I can try to help you here as well.

For the fields in which you're storing your aggregate result, are you marking them as Read-Only on the page layout or in the User Profiles?

**Comment by aheber** [comment]
@Stephen-J-Russell can you provide some details. Are you talking about the field that is the result field on the parent object, or the field that actually lives on the DLRS configuration object?

DLRS is setup to write to the Parent's field no matter the user's permissions. It can be setup to respect sharing settings if desired.

If DLRS refused to update the parent depending on a user's settings then the field would fall out of sync with the actual data.

If you'd like to avoid users being able to cause writes to a parent's field then you'll need to use the Scheduled or Scheduled Full Calculate modes instead of Realtime and the Scheduled Apex should. be run as a user with the proper access.


If there is something else happening and I've totally missed the mark please feel free to clarify for me and we can go from there.
