### ISSUE TITLE
Data sync failure - DLRS - Account Trigger -error ID: 1114621756-24822 (1270194348)"

### ISSUE THREAD

**Issue by cnwufo** [SFDO-Community/declarative-lookup-rollup-summaries#1215]
We are experiencing data sync issues: I receive the message "Got an unexpected error while processing BULK-API. Contact support with error ID: 1114621756-24822 (1270194348)". 
 

Same thing was seen in the debug log when we tried to update the owner of the Account record which  I inserted.  When we compare the debug logs and the error that salesforce is getting in server logs, the issue seems to be coming from package 'Declarative Lookup Rollup Summaries Tool' which has a Trigger on Account object.
 

Can you please look into the issue. In the same vein, salesforce support is asking for permission to enable managed package logs for DLRS. 

Please help look into the issue. Current version we are running on is  2.9.

**Comment by aheber** [comment]
@cnwufo I'm not going to have the specific details of your situation. Most of the time we see issues like this when a child is updated and the system attempts to rollup to the parent record but that parent record isn't compatible with all the validation rules currently active in the org. 

My recommendation is to do some testing in a sandbox and try to update to the latest version. 2.9 is many years old and lots of improvements for failure modes have been implemented over time.

If you're still having issues with the latest release then please let me know and we an work more to dig down to the root cause.

Thanks!
