### ISSUE TITLE
When Scheduled flow runs we are receiving this Error message "CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY: dlrs_SBQQ_SubscriptionTrigger"

### ISSUE THREAD

**Issue by sherineraj** [SFDO-Community/declarative-lookup-rollup-summaries#1241]
**Is your feature request related to a problem? Please describe.**
We have Scheduled flow that runs daily but looks like from few days the flows is not updating the records and we received an Error Email after the at the same time.
**Error message:**Error element Update_Current_Term_on_Subscription (FlowRecordUpdate).
The flow tried to update these records: xxxxxxxxx. This error occurred: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY: dlrs_SBQQ_SubscriptionTrigger: execution of AfterUpdate caused by: System.DmlException: Update failed. First exception on row 0 with id xxxxxxxxx; first error: UNABLE_TO_LOCK_ROW, unable to obtain exclusive access to this record: [] (dlrs) Trigger.dlrs_SBQQ_SubscriptionTrigger: line 7, column 1. You can look up ExceptionCode values in the [SOAP API Developer Guide](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_calls_concepts_core_data_objects.htm#).---The flow tried to update these records: xxxxxxxxx. This error occurred: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY: dlrs_SBQQ_SubscriptionTrigger: execution of AfterUpdate caused by: System.DmlException: Update failed. First exception on row 0 with id xxxxxxxxx; first error: UNABLE_TO_LOCK_ROW, unable to obtain exclusive access to this record: [] (dlrs) Trigger.dlrs_SBQQ_SubscriptionTrigger: line 7, column 1. You can look up ExceptionCode values in the [SOAP API Developer Guide](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_calls_concepts_core_data_objects.htm#)

**Describe the solution you'd like**
We would like to resolve this Error. We tried changing the scheduled time but still we receive the same error

**Comment by aheber** [comment]
The causes of locking situations can come from many places. You might want to review what else is running in your system during that time. Are the DLRS rollups happening via Scheduled Full Calculate, or are they real-time configured and running as a result of the Scheduled Flow taking action?

Can you provide some more details on your specific rollup configuration so we can better understand what the system is doing?

Our recommended channel for support is the Trailblazer Community Group for DLRS, most of our excellent community members who would be able to help you hang out there.

Hopefully we can find the root cause if this is still happening to your system.
