### ISSUE TITLE
List has no rows for assignment to SObject

### ISSUE THREAD

**Issue by ktallman** [SFDO-Community/declarative-lookup-rollup-summaries#1246]
**Describe the bug**
When I try to deploy a child trigger, I get this error:

List has no rows for assignment to SObject (workstudy): [] (dlrs) Class.dlrs_workstudy_EmploymentTest.testTrigger: line 11, column 1

I also get this warning:
dlrs_workstudy_EmploymentTrigger:Test coverage of selected Apex Trigger is 0%, at least 75% test coverage is required

**To Reproduce**

1. Create new DLRS using new wizard or creating DLRS manually
2. click on "Manage Child Trigger"
3. Click on "Deploy"
5. See error

**Expected behavior**
Expect child trigger to deploy successfully so I can proceed with deploying the DLRS

**Screenshots**
![DLRS Error page](https://user-images.githubusercontent.com/9255428/187259679-81ed5edd-9c15-4b68-8014-f5e75b7a4d46.png)

**Additional context**

**Comment by aheber** [comment]
@ktallman this error is usually caused by the child record needing more detailed setup for the Apex Test that would be used to cause the trigger to fire.

DLRS provides a method to customize the test method body to suite your data better. If you're not familiar with writing Apex test code for you system you may need to engage a developer who understands your systems requirements and can do the customizations for you.
