### ISSUE TITLE
DLRS Error when rolling up FinancialForce Timecard counts to Project

### ISSUE THREAD

**Issue by Ckeds3** [SFDO-Community/declarative-lookup-rollup-summaries#1257]
I have created a new DLRS to run a count of FinancialForce Timecards up to the related Project LookUp field. I'm getting the error in the attached image: "Timecard Header must specify a Project.: [pse__Project__c]". When I posted this to FinancialForce support, they believe the DLRS is attempting to test the process by creating a new Timecard but doesn't know what project value to populate in the required project field. The validation is part of a managed package trigger. Any suggestions on how to resolve this so I can get the record counts at the Project level?
![DLRS Error](https://user-images.githubusercontent.com/116203137/196771251-0e4bff51-6937-4bee-bf0e-80f055fff360.png)

**Comment by jolsonmda** [comment]
I would add a Test Code (Child Object) information in that pulls in the project id. When I did the rollups for the transactions on projects, I had to add in this "update [select Id from c2g__codaTransactionLineItem__c limit 1];" before it would do the rollup and I had to check the Test Code See All Data. You might not have to add the Test Code See All Data check box for timecards. so maybe try "update [select Id from pse__Proj__c limit 1];", minus the quotes of course.

**Comment by aheber** [comment]
@Ckeds3 were you able to get this resolved using the notes from @jolsonmda?

I think there have been other specific examples for FF PSA both on this project and in the Trailblazer Community Group for DLRS. I would search those archives. 

DLRS doesn't have the ability to know what your system needs to save a record because all systems can be different. You'll have to help it by customizing the Test Code portion of the DLRS configuration.
