### ISSUE TITLE
Performing Update on child record does not trigger roll-up calculation

### ISSUE THREAD

**Issue by baobao917** [SFDO-Community/declarative-lookup-rollup-summaries#1496]
**Describe the bug**
I am attempting to trigger the rollup calculation on existing records by performing a Update of RecordId on existing records.  In the past this would have triggered the roll-up to fire and calculate.  Now nothing happens.  Have v2.21 installed

However, if I create/clone a new child record, the rollup does calculate OR if I perform a full recalculate, the rollup does calculate (proving the rollup works/configured correctly).

**To Reproduce**

1. Go to pre-existing child record of rollup calculation.  
2. Click Edit and Save
3. Go to the target rollup field on the parent. 
4. The target rollup field has not changed 

**Expected behavior**
Rollup calculation should have fired when an update operation occurred on the child record.  Per your own DLRS documentation, this should be occurring.
![image](https://github.com/user-attachments/assets/6f3a17f9-3e72-4945-83fd-5f6f7a7de26c)

**Screenshots**
https://www.loom.com/share/e399ec4efa04451ca509c61df656bdc5

**Additional context**

**Comment by aheber** [comment]
@baobao917 thank you for reporting this. Without specific details I can't know for sure but the documentation isn't quite correct there. 

In the future, I'd suggest you start by posting questions like this to the [Trailblazer Community Group](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5p) for DLRS.

DLRS attempts to be careful about updates. It will only reprocess the rollup configuration when a record is updated and one of the fields it cares about are changed. The Relationship Field, Field to Rollup, or any of the fields listed in Relationship Criteria Fields. It compares the old and new values during an update and if any of them have changed then it causes the rollup to occur.

If you're simply re-saving the record but not changing any of those values as part of that save then DLRS will not execute the rollup in an effort to be efficient with the system resources. This can be a particular problem for things like formula fields that references related objects through a Lookup, or Relationship Criteria that directly references parent/lookup values. (adding an deleting child records works because DLRS doesn't have old/new values for those so they automatically cause recalculation attempts)

DLRS has had this behavior for a very long time. I'm not sure what you experienced when you say it used to work. In v2.19 (I think) we added a new behavior where even if the rollup is calculated, if the calculated value matches the value already on the parent then it doesn't perform the DML action because it wouldn't result in a different value. That doesn't sound like what you're dealing with but there is a checkbox in the Custom Setting for DLRS to disable that behavior if you think you need it.

**Comment by baobao917** [comment]
@aheber Thanks for the quick response.  Maybe I'm thinking of a different rollup tool that behaves that way.  Thank you for clarifying.  That is the exact issue I'm having b/c one of the relationship fields is a formula field referencing a parent object.  I will just perform a full recalculation and that should solve my issue.

**Comment by aheber** [comment]
Depending on your use case you could have a few options.

If you use the "Process Builder" mode but actually through Flow (it is just an Invocable Action) then you can use Flow to tell DLRS when to recalculate the rollup. If you know your logic then you could intelligently prompt a recalculation for specific rollups for specific parent records.

Other options, put a random text field on the record and just put a random value in there, or a number and increment the number. You can then tell the rollup via Relationship Criteria Fields that this field should be monitored, anytime you change the value to anything different then it will fire the rollup. That would give you a lot of ways to update that value and force the rollup to update.

Hopefully you can find something that works for you.

**Comment by aheber** [comment]
Moving this to closed, if you need additional help remember the [Trailblazer Community Group](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5p) is the best place to find it.
