### ISSUE TITLE
Type name too long, maximum length is 40

### ISSUE THREAD

**Issue by mobrienffdc** [SFDO-Community/declarative-lookup-rollup-summaries#25]
Getting the following error when trying to Deploy the trigger:

ERROR  
Error:
classes/dlrs_ffrr_RevenueRecognitionTransactionLineTest.cls (Line: 5: Column:15) : Type name too long, maximum length is 40: dlrs_ffrr_RevenueRecognitionTransactionLineTest

Any way to work around the 40 character limit?

**Comment by Charlton-H** [comment]
@afawcett I'm new to your awesome tool-- and I just received this error-- "Value too long for field: fullName maximum length is:40 (FIELD_INTEGRITY_EXCEPTION)" and I'm not sure how to handle this situation. I'm reading the comments here and saw that this was fixed in v1.10? Not sure where to go from here, do you mind lending a hand or providing direction? would greatly appreciate it! Thanks
