### ISSUE TITLE
Issue when Advanced Currency Management is enabled

### ISSUE THREAD

**Issue by SouadSalhi** [SFDO-Community/declarative-lookup-rollup-summaries#40]
Hi,
It seems that there is an issue when Advanced Currency Management is enabled.
We added a field at Account level to calculate sum of Opportunities amounts in a certain stage.
For example, we have Opportunities in HKD and the Account is also in HKD.
At Opportunity level we have the amount in HKD and in parenthesis the GBP converted amount. 
ex at Opp level : HKD 110 000 (GBP 8500)
At Account level we have the HKD sign and the GBP converted amount (instead of the HKD amount) and then in parenthesis another conversion of the GBP amount (which is wrong as based on the incorrect value).
ex at ACC level (with 1 opp only against this account): HKD 8500 (GBP 685)
Thank you for your help

**Comment by jack071900** [comment]
Can you provide clarity as to how this works and options for various use cases? Does DLRS rollup the native or corporate master currency? We prefer the native because the field on the account will automatically convert to corporate. We have a use case where we rollup to two fields on the account and then sum the two DLRS fields. Hence they go through currency conversion twice, which leads to a wrong value.
