### ISSUE TITLE
DLRS jobs stopped calculating

### ISSUE THREAD

**Issue by ktallman** [SFDO-Community/declarative-lookup-rollup-summaries#954]
This job used to work, but has stopped working without any error or explanation why. I have tried forcing the calculation but everything still comes up zeros. I have attached a screenshot of the configuration.

Expected behavior:  Whenever a new "Application" is created (custom object), and there is a Referring Organization listed (Lookup:Account), then the system should populate a field on the related Account record (Inbound Referral Count) with the total number of referred Application records that were created in the last 12 months.

![DLRS Inbound Referral Count](https://user-images.githubusercontent.com/9255428/85075902-6febb200-b17c-11ea-8490-354843cfe465.jpg)

**Comment by afawcett** [comment]
Hi @ktallman - this may only have been working on create of such records - basically using date based criteria does not work in realtime - as the tool does not know when re-evaluate it - since it only (in relatime mode) - realcs when field values change - and CreatedDate value does not change. What you need to do is use one of the scheudle modes - probably full recalc - please have a read through this -  https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/What-you-need-to-know-about-Scheduling-Rollups

**Comment by aheber** [comment]
Marking this as resolved and closing.

If you need further assistance please reach out to the Trailblazer Community Group for DLRS which is our preferred channel for providing support.
