### ISSUE TITLE
NPSP Contact Merge throwing error related to shadow records

### ISSUE THREAD

**Issue by nonprofitdatageeks** [SFDO-Community/declarative-lookup-rollup-summaries#963]
This org just installed 2.12 and built a new rollup a couple months ago.  The rollup is on Account and calculates data from the Contact record.  It is a realtime calculation.  When they try to use the NPSP Contact Merge they get the error in the screenshot.  The Lookup Rollup Summaries Tools tab is blank.  Ideas on how to resolve this issue?

Here is the text of the error - "Scheduled rollups are running in legacy mode and are unable to resolve corresponding shadow rollups. Please visit the Lookup Rollup Summary Tools rab for more information and steps to resolve."

![DLRS Contact Merge Issue](https://user-images.githubusercontent.com/34165316/87803630-60619680-c818-11ea-8df9-24dbe6cf1d57.jpg)

**Comment by afawcett** [comment]
@nonprofitdatageeks did you try following the instructions in the error message? Was there a problem doing that?

**Comment by nonprofitdatageeks** [comment]
Yes, when I visit the Lookup Rollup Summaries Tools tab as directed there is no content, just the title header...

**Comment by nonprofitdatageeks** [comment]
@afawcett Any insights on this issue?  Please advise.  Thanks!

**Comment by nonprofitdatageeks** [comment]
@afawcett We have had to turn off rollups at this org in order to be able to merge contacts. Any additional info that could be helpful?

**Comment by djtsystems** [comment]
@afawcett , I'm also seeing the same thing but with a different notification.
![Merge error](https://user-images.githubusercontent.com/70650413/91999869-e07d8600-ed0a-11ea-830c-e8621781e515.JPG)

**Comment by RealEvanPonter** [comment]
@afawcett I'm also seeing the same issue as the OP. Attempting to merge accounts will show this message. Visiting the "Lookup Rollup Summaries Tools tab shows a header and no content. Are you able to post the steps from that page here so we can review them?

**Comment by RealEvanPonter** [comment]
I found the page that lists the steps to resolve this error:

https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/Attention:-Need-to-delete-unused-field-on-dlrs__LookupRollupSummaryScheduleItems__c

1. Run a report or create list view on the Lookup Rollup Summary Schedule Items object that filters for records that do not contain a value in the Lookup Rollup Summary 2 field. If you have records like this its possible they are very old, since this field has been being populated since v1.15 and beyond. If you want you can delete these records and re-run a full calculate for the associated Rollups.
2. Next you need to go to the Object Manager in Setup and find the Lookup Rollup Summary Schedule Items object. Locate the field Lookup Rollup Summary (its a Master-Detail) with the API name dlrs__LookupRollupSummary__c.
3. Delete this field and don't worry about accidentally deleting others the platform will block this. This will not effect any other data in your org as it is was purely used for the operation of the tool in prior releases and is now no longer needed.

**Comment by TiminMaine** [comment]
I'm attempting this fix and for some reason am unable to delete the dlrs__LookupRollupSummary__c field. From the field list, I only have "Edit" as an option, and not delete. I have all the necessary permissions. The system also indicates that this is no longer part of the managed package and that it can be deleted, but there is simply no delete option. Any thoughts?

**Comment by AMG7525** [comment]
@TiminMaine I had this same issue. You have to switch to classic and the delete option is available there.

**Comment by TiminMaine** [comment]
Thanks, @AMG7525 - I found the same thing and posted on the Hub and forgot to post here. What was strange is that I did not have the same experience in my production org. The Delete option was there. I am curious as to why there was a difference, but now that everything is working, I guess it doesn't matter. Thanks.

**Comment by afawcett** [comment]
Updated the docs - thanks all

**Comment by aheber** [comment]
Marking this as closed. The docs were updated but if further updates are needed please heads over to https://github.com/SFDO-Community-Sprints/DLRS-Documentation and help us make any changes needed.
